---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LENOVO.
--- DateTime: 2026/1/15 10:44
---

--===========================
--article toggle favorite
--===========================
--KEYS[1] = article:favorite:{articleId}
--KEYS[2] = article:favorite:add:{articleId}:v{current}
--KEYS[3] = article:favorite:del:{articleId}:v{current}
--KEYS[4] = article:favorite:count:{articleId}
--KEYS[5] = article:favorite:update
--
--ARGV[1] = userId
--ARGV[2] = articleId
--=============================

redis.call("SADD", KEYS[5], ARGV[2]);
if redis.call("SISMEMBER", KEYS[1], ARGV[1]) == 1 then
    redis.call("SREM", KEYS[1], ARGV[1]);
    redis.call("DECR", KEYS[4]);
    if redis.call("SISMEMBER", KEYS[2], ARGV[1]) == 1 then
        redis.call("SREM", KEYS[2], ARGV[1]);
    else
        redis.call("SADD", KEYS[3], ARGV[1]);
    end
    return 0
else
    redis.call("SADD", KEYS[1], ARGV[1]);
    redis.call("INCR", KEYS[4]);
    if redis.call("SISMEMBER", KEYS[3], ARGV[1]) == 1 then
        redis.call("SREM", KEYS[3], ARGV[1]);
    else
        redis.call("SADD", KEYS[2], ARGV[1]);
    end
    return 1
end