-----
----- Generated by EmmyLua(https://github.com/EmmyLua)
----- Created by LENOVO.
----- DateTime: 2026/1/17 17:36
-----
--
--=====================
--commit cache
--=====================
--KEYS[1] = SET_KEY
--KEYS[2] = COUNT_KEY
--KEYS[3] = INIT_KEY
--
--ARGV[1] = ttl
--ARGV[2..] = userIds
--=====================




redis.call("SADD", KEYS[1], unpack(ARGV, 2))

redis.call("SET", KEYS[3], "READY")

redis.call("SET", KEYS[2], #ARGV - 1)

redis.call("EXPIRE", KEYS[1], ARGV[1])
redis.call("EXPIRE", KEYS[2], ARGV[1])
redis.call("EXPIRE", KEYS[3], ARGV[1])
