---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LENOVO.
--- DateTime: 2026/1/17 17:07
---

--============================
--ensure cache
--============================
--KEYS[1] = SET_KEY
--KEYS[2] = COUNT_KEY
--KEYS[3] = INIT_KEY
--
--ARGV[1] = ttl
--ARGV[2] = loading ttl
--============================

local status = redis.call("GET", KEYS[3])
if status == "READY" then
    redis.call("EXPIRE", KEYS[1], ARGV[1])
    redis.call("EXPIRE", KEYS[2], ARGV[1])
    redis.call("EXPIRE", KEYS[3], ARGV[1])
    return 1
end

if status == "loading" then
    return 2
end

redis.call("SET", KEYS[3], "LOADING", "EX", ARGV[2])

return 0